spring:
  datasource:
    url: jdbc:mysql://localhost:3307/db_example?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  config: mybatis-config.xml
  type-aliases-package: com.example.demo.model
  mapper-locations: mybatis/mapper/*.xml